#index:
#    path: /
#    controller: App\Controller\DefaultController::index
pickaplace:
    path: /
    controller: App\Controller\FrontController::pickaplace

index:
    path: /place
    controller: App\Controller\FrontController::place